export const typeSelectOptions = [
  { value: "none", text: "なし" },
  { value: "normal", text: "ノーマル" },
  { value: "fire", text: "ほのお" },
  { value: "water", text: "みず" },
  { value: "electric", text: "でんき" },
  { value: "grass", text: "くさ" },
  { value: "ice", text: "こおり" },
  { value: "fighting", text: "かくとう" },
  { value: "poison", text: "どく" },
  { value: "ground", text: "じめん" },
  { value: "flying", text: "ひこう" },
  { value: "psychic", text: "エスパー" },
  { value: "bug", text: "むし" },
  { value: "rock", text: "いわ" },
  { value: "ghost", text: "ゴースト" },
  { value: "dragon", text: "ドラゴン" },
  { value: "dark", text: "あく" },
  { value: "steel", text: "はがね" },
  { value: "fairy", text: "フェアリー" },
];
